name: Tests

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-slim
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22.14
          cache: npm

      - run: npm ci

      - run: npx playwright install chromium --with-deps

      - name: Run tests
        run: xvfb-run --auto-servernum npm test
